tasks:
  - name: Install Faunadb
    init: |
      docker pull fauna/faunadb:4.15.0
    command: gp sync-done images_pulled
  
  - name: Init Next.js App
    init: |
      cd app
      npm i
    command: gp sync-done next_packages_initialized

  - name: Init Strapi App
    init: |
      cd cms
      npm i
      npm run build
      cd ..
    command: gp sync-done strapi_packages_initialized && sh gitpod-scripts/strapi.sh
  
  - name: Start build
    command: |
      gp sync-await images_pulled && 
      gp sync-await next_packages_initialized && 
      gp sync-await strapi_packages_initialized && 
      sh gitpod-scripts/startCloudDevEnv.sh

ports:
  - port: 3000
    onOpen: open-browser
    name: RC4Community
    description: Next.js app for RC4Community
  - port: 1337
    onOpen: notify
    name: Strapi
    description: Strapi Dashboard
  - port: 8084
    onOpen: ignore
  - port: 8444
    onOpen: ignore
  - port: 8443
    onOpen: ignore

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: true
    addBadge: true