# tasks:
#   - name: Setup & Build RC4Community
#     command: sh startdevenv.sh

ports:
  - port: 3000
    onOpen: open-browser
    name: RC4Community
    description: Next.js app for RC4Community
  - port: 1337
    onOpen: notify
    name: Strapi
    description: Strapi Dashboard

image: fauna/faunadb