tasks:
  - name: Install Faunadb
    init: |
      docker pull fauna/faunadb:4.15.0
      gp sync-done build1
  
  - name: Init Next.js App
    init: |
      cd app
      npm i
      gp sync-done build2

  - name: Init Strapi App
    init: |
      cd cms
      npm i
      gp sync-done build3
  
  - name: Start build
    command: gp sync-await build1 && gp sync-await build2 && gp sync-await build && sh gitpod-scripts/startCloudDevEnv.sh

ports:
  - port: 3000
    onOpen: open-browser
    name: RC4Community
    description: Next.js app for RC4Community
  - port: 1337
    onOpen: notify
    name: Strapi
    description: Strapi Dashboard

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: true
    addBadge: true